name: Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: ['opened', 'synchronize']

# Cancel redundant workflows.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    name: 💅 Lint
    runs-on: ubuntu-latest
    steps:
      - name: 🎯 Checkout
        uses: actions/checkout@v3

      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: 💅 Lint
        run: pnpm format && pnpm lint

  # test:
  #   name: 🧪 Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 🎯 Checkout
  #       uses: actions/checkout@v3
  #
  #     - name: 🔧 Setup pnpm
  #       uses: pnpm/action-setup@v2
  #       with:
  #         version: 8
  #         run_install: |
  #           - recursive: true
  #             args: [--frozen-lockfile, --strict-peer-dependencies]
  #     - name: 🧪 Test
  #       run: pnpm test

  build:
    name: 🏭 Build
    # This job will run after the lint job is completed.
    # In case the project has test, uncomment the test job
    # and add it to the `needs` list.
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: 🎯 Checkout
        uses: actions/checkout@v3

      - name: 🔧 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: 🏭 Build
        run: pnpm build
